import streamlit as st
import pandas as pd
import numpy as np

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Solar Flare Forecasting System",
    page_icon="☀️",
    layout="wide"
)

# ---------------- CUSTOM CSS ----------------
st.markdown("""
<style>
    .main {
        background-color: #0b1020;
    }

    .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
    }

    .title {
        font-size: 38px;
        font-weight: 700;
        margin-bottom: 5px;
    }

    .subtitle {
        color: #9ca3af;
        font-size: 17px;
        margin-bottom: 25px;
    }

    .card {
        background-color: #151c2f;
        padding: 22px;
        border-radius: 14px;
        border: 1px solid #26304a;
        margin-bottom: 18px;
    }

    .prediction {
        background-color: #1d2438;
        padding: 30px;
        border-radius: 16px;
        border: 1px solid #39445f;
        text-align: center;
    }

    .prediction-class {
        font-size: 46px;
        font-weight: 800;
        margin: 10px 0;
    }

    .small-text {
        color: #9ca3af;
        font-size: 14px;
    }

    .pipeline {
        text-align: center;
        font-size: 18px;
        font-weight: 600;
        padding: 20px;
        background-color: #151c2f;
        border-radius: 14px;
        border: 1px solid #26304a;
    }
</style>
""", unsafe_allow_html=True)


# ---------------- HEADER ----------------
st.markdown(
    '<div class="title">☀️ Solar Flare Forecasting System</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">'
    'Multimodal Deep Learning for Solar Flare Classification and Forecasting'
    '</div>',
    unsafe_allow_html=True
)

# ---------------- STATUS ----------------
status1, status2, status3 = st.columns(3)

with status1:
    st.metric("System Status", "● ONLINE")

with status2:
    st.metric("Observation Mode", "HMI + AIA")

with status3:
    st.metric("Forecast Window", "24 Hours")


# ---------------- SOLAR OBSERVATIONS ----------------
st.markdown("## 🔭 Solar Observations")

col1, col2 = st.columns(2)

with col1:
    st.markdown('<div class="card">', unsafe_allow_html=True)

    st.subheader("HMI Magnetogram")

    st.info(
        "HMI magnetogram image will appear here when the real solar "
        "observation data is connected."
    )

    st.caption("Input → Solar magnetic-field information")

    st.markdown('</div>', unsafe_allow_html=True)


with col2:
    st.markdown('<div class="card">', unsafe_allow_html=True)

    st.subheader("AIA UV Observation")

    st.info(
        "AIA UV image will appear here when the real solar "
        "observation data is connected."
    )

    st.caption("Input → Ultraviolet solar observation")

    st.markdown('</div>', unsafe_allow_html=True)


# ---------------- MODEL PIPELINE ----------------
st.markdown("## 🧠 Multimodal Deep Learning Pipeline")

st.markdown("""
<div class="pipeline">

HMI Magnetogram → <b>Magnetogram CNN</b>
&nbsp;&nbsp; + &nbsp;&nbsp;
AIA UV Image → <b>UV CNN</b>

<br><br>

↓

<br><br>

<b>Multimodal Feature Fusion</b>

<br><br>

↓

<br><br>

<b>Attention-Based Spatial-Temporal Model</b>

<br><br>

↓

<br><br>

🔥 <b>A / B / C / M / X Flare Prediction</b>

</div>
""", unsafe_allow_html=True)


# ---------------- PREDICTION ----------------
st.markdown("## 🔥 Flare Prediction")

pred_col1, pred_col2 = st.columns([1, 2])

with pred_col1:
    st.markdown("""
    <div class="prediction">
        <div class="small-text">PREDICTED FLARE CLASS</div>
        <div class="prediction-class">M</div>
        <div class="small-text">DEMO OUTPUT — MODEL NOT CONNECTED</div>
    </div>
    """, unsafe_allow_html=True)

with pred_col2:
    st.markdown('<div class="card">', unsafe_allow_html=True)

    st.subheader("Flare Classes")

    flare_data = pd.DataFrame({
        "Class": ["A", "B", "C", "M", "X"],
        "Status": [
            "Possible",
            "Possible",
            "Possible",
            "Possible",
            "Possible"
        ]
    })

    st.dataframe(
        flare_data,
        use_container_width=True,
        hide_index=True
    )

    st.caption(
        "The final prediction will be generated by the trained "
        "multimodal deep-learning model."
    )

    st.markdown('</div>', unsafe_allow_html=True)


# ---------------- TEMPORAL ANALYSIS ----------------
st.markdown("## 📈 Temporal Solar Activity")

demo_activity = pd.DataFrame({
    "Time Step": range(1, 11),
    "Relative Activity": [
        0.32, 0.38, 0.41, 0.46, 0.53,
        0.58, 0.62, 0.69, 0.74, 0.81
    ]
})

st.line_chart(
    demo_activity.set_index("Time Step")
)

st.caption(
    "Demo visualization — will be replaced by temporal solar "
    "observation/model data."
)


# ---------------- PERFORMANCE ----------------
st.markdown("## 📊 Model Evaluation")

m1, m2, m3, m4 = st.columns(4)

with m1:
    st.metric("Accuracy", "—")

with m2:
    st.metric("Precision", "—")

with m3:
    st.metric("Recall", "—")

with m4:
    st.metric("F1 Score", "—")


# ---------------- INTERPRETATION ----------------
st.markdown("## 🔬 Case Study & Interpretation")

st.markdown("""
<div class="card">

<b>Selected Solar Event</b>

<br><br>

HMI and AIA observations → modality-specific feature extraction
→ multimodal fusion → spatial-temporal analysis
→ flare-class prediction.

<br><br>

The case-study section will be connected to real historical
solar observations after the model and dataset are integrated.

</div>
""", unsafe_allow_html=True)


# ---------------- FOOTER ----------------
st.markdown("---")

st.caption(
    "Solar Flare Forecasting System | Multimodal Deep Learning Prototype"
)
